//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidlyDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int MovieId { get; set; }
        public string MovieName { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public System.DateTime DateAdded { get; set; }
        public short NumberInStock { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual MovieCategory MovieCategory { get; set; }
    }
}
